### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by SHyun-Lee** [Sebongbak/DSEC#1]
sequence.py

from pathlib import Path
import weakref

import cv2
import h5py
import numpy as np
import torch
from torch.utils.data import Dataset

from dataset.representations import VoxelGrid
from utils.eventslicer import EventSlicer

class Sequence(Dataset):

1.      **### def __init__(self, seq_path: Path = 'C:\Users\hase0\OneDrive\바탕 화면\Dataset\thun_00_a_events_left', mode: str='train', delta_t_ms: int=50, num_bins: int=15):**

**Comment by Sebongbak** [comment]
visualization -> eventreader.py

class EventReaderAbstract:

1.     def __init__(self, filepath: Path = "C:\Users\hase0\OneDrive\바탕 화면\Dataset\thun_00_a_events_left\events.h5"):

        assert filepath.is_file()
        assert filepath.name.endswith('.h5')
        self.h5f = h5py.File(str(filepath), 'r')
        self._finalizer = weakref.finalize(self, self.close_callback, self.h5f)

**Comment by Sebongbak** [comment]
eventvideo.py

if __name__ == '__main__':
    parser = argparse.ArgumentParser('Visualize Events')
    parser.add_argument('event_file', type=str, help='Path to events.h5 file')
    parser.add_argument('output_file', help='Path to write video file')
    parser.add_argument('--delta_time_ms', '-dt_ms', type=float, default=50.0, help='Time window (in milliseconds) to summarize events for visualization')
    args = parser.parse_args()

    event_filepath = Path(args.event_file)
    video_filepath = Path(args.output_file)
    dt = args.delta_time_ms

    height = 480
    width = 640

    assert video_filepath.parent.is_dir(), "Directory {} does not exist".format(str(video_filepath.parent))

    writer = skvideo.io.FFmpegWriter(video_filepath)
    for events in tqdm(EventReader(event_filepath, dt)):
        p = events['p']
        x = events['x']
        y = events['y']
        t = events['t']
        img = render(x, y, p, height, width)
        writer.writeFrame(img)
    writer.close()

**Comment by Sebongbak** [comment]
eventvideo.py

if __name__ == '__main__':
    parser = argparse.ArgumentParser('Visualize Events')
    parser.add_argument('event_file', type=str, help='Path to events.h5 file')
    parser.add_argument('output_file', help='Path to write video file')
    parser.add_argument('--delta_time_ms', '-dt_ms', type=float, default=50.0, help='Time window (in milliseconds) to summarize events for visualization')
    args = parser.parse_args()

    event_filepath = Path(args.event_file)
    video_filepath = Path(args.output_file)
    dt = args.delta_time_ms

    height = 480
    width = 640

    assert video_filepath.parent.is_dir(), "Directory {} does not exist".format(str(video_filepath.parent))

    writer = skvideo.io.FFmpegWriter(video_filepath)

1.     for events in tqdm(EventReader(event_filepath, dt)):

        p = events['p']
        x = events['x']
        y = events['y']
        t = events['t']
        img = render(x, y, p, height, width)
        writer.writeFrame(img)
    writer.close()


- [ 1.]  error : usage: Visualize Events [-h] [--delta_time_ms DELTA_TIME_MS]
                        C:/Users/hase0/OneDrive/바탕 화면/events.h5 C:/Users/hase0/OneDrive/바탕 화면/output.mp4
Visualize Events: error: the following arguments are required: C:/Users/hase0/OneDrive/바탕 화면/events.h5, C:/Users/hase0/OneDrive/바탕 화면/output.mp4

**Comment by Sebongbak** [comment]
d
